version: 2
jobs:
  build:
    working_directory: /go/src/github.com/henry40408/concourse-ssh-resource
    docker:
      - image: circleci/golang:1.9
      - image: quay.io/henry40408/alpine-ssh:v1.1.0
    steps:
      - checkout
      - run: go get -u github.com/kardianos/govendor
      - restore_cache:
          key: dependency-cache-{{ checksum "vendor/vendor.json" }}
      - run: govendor sync
      - save_cache:
          key: dependency-cache-{{ checksum "vendor/vendor.json" }}
          paths:
            - ./vendor
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
